[package]
name = "ttpgen"
version = "0.1.0"
edition = "2024"

[dependencies]
roxmltree = "0.20.0"
hungarian = "1.1.1"
log = "0.4.28"
env_logger = "0.11.8"
chrono = "0.4.42"
itertools = "0.14.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"